import time

def barrett_reduce(x, N, mu, k):   
    q = (x * mu) >> k  
    r = x - q * N
    
    while r >= N:
        r -= N
    return r

N = 2^50-1
x = 2^125
k = N.nbits()  
mu = (1 << k) // N  

start = time.time()
res1 = x % N
t1 = time.time() - start

start = time.time()
res2 = barrett_reduce(x, N, mu, k)
t2 = time.time() - start
if (res1==res2):
    print(f"%: {t1:.6f} sec")
    print(f"Barrett:{t2:.6f} sec")
